# cas de test de rev_wdmatch (une ligne = un test)
t 'abc' 'xcxbxa'
t 'abc' 'abc'
t 'faya' 'ayaf'
t 'nuit' 'tiun'
t 'nuit' 'nuit tiun'
t '' 'abc'
t 'abc' ''
t 'abc'
t
t 'aa' 'a'
t 'aa' 'aba'
t 'quarante deux' 'xuedq etnarauq'
t 'zut' 'tuzzz'
t 'a b' 'b a'
