# cas de test de ft_interdup (une ligne = un test)
t 'padinton' 'paqefwtdjetyiytjneytjoeyjnejeyj'
t 'ddf6vewg64f' 'gtwthgdwthdwfteewhrtag6h4ffdhsd'
t 'rien' 'cette phrase ne cache rien'
t 'abc' 'xyz'
t '' 'abc'
t 'abc' ''
t 'aaaa' 'a'
t 'Hello' 'hello'
t '  a  b  ' ' b'
