# cas de test de nth_word (une ligne = un test)
t '  les   dauphins  sont   la ' '2'
t '   un deux trois' '3'
t 'un deux' '3'
t 'un deux' '0'
t '     ' '1'
t 'un deux'
t '' '1'
t $'\t\tfirst\t\tsecond ' '2'
t 'hello' '1'
t 'hello' '-1'
t 'a b c d e f g h i j k' '11'
t 'a b c d e f g h i j k' '12'
t '  mot  ' '1'
t 'a b c d e f g' '007'
t 'x y' '2147483647'
t
t 'a' '1' 'extra'
t '   il  etait   une fois  ' '4'
t 'un deux trois' '-2147483648'
t $'mot\t' '1'
